
export const assignmentsData = [
  // 9. Sınıf Edebiyat
  { id: 901, grade: 9, subject: "literature", title: "Sözün İnceliği: Şiir Tahlili", description: "Bir şiirin ahenk unsurlarını analiz etme.", instructions: "Temaya uygun bir şiir seç. Kafiye, redif ve söz sanatlarını gösteren renkli bir tablo hazırla.", formats: "PDF, Word", size: "5 MB" },
  { id: 902, grade: 9, subject: "literature", title: "Geçmişe Yolculuk: Dede Korkut Hikayesi", description: "Bir Dede Korkut hikayesini modern dile uyarlama.", instructions: "Seçtiğiniz bir Dede Korkut hikayesini günümüz Türkçesiyle yeniden yazın ve hikayeden bir sahneyi resmedin.", formats: "Word, JPG", size: "10 MB" },
  { id: 903, grade: 9, subject: "literature", title: "Sahnedeki Roman: Roman Uyarlaması", description: "Okunan bir romandan tiyatro sahnesi oluşturma.", instructions: "Okuduğunuz bir romandan en sevdiğiniz bölümü kısa bir tiyatro sahnesine dönüştürün. Diyalogları ve sahne direktiflerini yazın.", formats: "PDF", size: "2 MB" },
  { id: 904, grade: 9, subject: "literature", title: "Masaldan E-Postaya: Türler Arası Geçiş", description: "Bir halk masalını e-posta formatında yeniden yazma.", instructions: "Keloğlan gibi bilinen bir masalın olay örgüsünü, karakterlerin birbirine gönderdiği bir dizi e-posta olarak kurgulayın.", formats: "PDF", size: "1 MB" },
  { id: 905, grade: 9, subject: "literature", title: "Haberin Peşinde: Olay Metni", description: "Okulda yaşanan bir olayı haber metnine dönüştürme.", instructions: "Okulda gerçekleşen bir kermes, yarışma veya etkinliği 5N1K kuralına uygun bir şekilde haber metni olarak yazın.", formats: "Word", size: "2 MB" },
  { id: 906, grade: 9, subject: "literature", title: "Benim Biyografim: Anı ve Biyografi Farkı", description: "Kendi hayatınızdan bir kesiti anı türünde yazma.", instructions: "Hayatınızdaki önemli bir dönüm noktasını (ilk okul günü, bir başarı vb.) anı türünün özelliklerini kullanarak yazın ve biyografiden farklarını belirtin.", formats: "Word", size: "3 MB" },
  { id: 907, grade: 9, subject: "literature", title: "Gezginin Gözünden: Gezi Yazısı", description: "Yaşadığınız şehri bir turiste tanıtma.", instructions: "Yaşadığınız yerin tarihi ve turistik bir mekanını, bir gezi yazısı formatında, fotoğraflar eşliğinde tanıtın.", formats: "Canva, PDF", size: "15 MB" },
  { id: 908, grade: 9, subject: "literature", title: "Söz Sanatları Afişi", description: "Edebi sanatları görselleştirme.", instructions: "Tevriye, kinaye, mübalağa gibi en az 5 söz sanatını tanımlayan ve örnekler içeren yaratıcı bir infografik veya afiş tasarlayın.", formats: "Poster, JPG", size: "10 MB" },
  { id: 909, grade: 9, subject: "literature", title: "Şiir Sesi: Sesli Şiir Okuma", description: "Bir şiiri vurgu ve tonlamalara dikkat ederek seslendirme.", instructions: "Seçtiğiniz bir şiiri, anlamına uygun bir fon müziği eşliğinde etkili bir şekilde okuyarak ses kaydı oluşturun.", formats: "Ses Kaydı, MP3", size: "10 MB" },
  { id: 910, grade: 9, subject: "literature", title: "Hikayenin Haritası: Olay Örgüsü Şeması", description: "Okunan bir hikayenin yapı unsurlarını şema ile gösterme.", instructions: "Okuduğunuz bir hikayenin olay örgüsünü (serim, düğüm, çözüm), karakterlerini, zaman ve mekanını gösteren bir zihin haritası veya akış şeması hazırlayın.", formats: "Canva, PDF", size: "5 MB" },

  // 9. Sınıf Fizik
  { id: 931, grade: 9, subject: "physics", title: "Evdeki Vektörler", description: "Fiziksel niceliklerin sınıflandırılması.", instructions: "Evinizde bulduğunuz 5 skaler ve 5 vektörel büyüklüğü fotoğraflayarak açıklayın. (Örn: Kapının koluna uygulanan kuvvet - vektörel).", formats: "Canva, PDF", size: "20 MB" },
  { id: 932, grade: 9, subject: "physics", title: "Özkütle Kulesi Deneyi", description: "Maddelerin özkütlelerini karşılaştırma.", instructions: "Su, zeytinyağı, bal gibi farklı yoğunluktaki sıvıları kullanarak bir özkütle kulesi oluşturun ve bu olayın nedenini açıklayan bir deney raporu yazın.", formats: "Word, PDF", size: "5 MB" },
  { id: 933, grade: 9, subject: "physics", title: "Dayanıklılık ve Karıncalar", description: "Canlılarda dayanıklılık ve kesit alanı/hacim ilişkisi.", instructions: "Bir karıncanın kendi ağırlığının kat kat fazlasını nasıl taşıyabildiğini, dayanıklılığın kesit alanı/hacim oranıyla ilişkisini kullanarak açıklayan bir sunum hazırlayın.", formats: "Görsel Sunum", size: "10 MB" },
  { id: 934, grade: 9, subject: "physics", title: "Sürat ve Hız Farkı", description: "Konum, alınan yol, yer değiştirme, sürat ve hız kavramları.", instructions: "Evinizden okula giderken kullandığınız yolu bir harita üzerinde çizin. Aldığınız yolu, yer değiştirmenizi, ortalama sürat ve hızınızı hesaplayarak karşılaştırın.", formats: "JPG, PDF", size: "8 MB" },
  { id: 935, grade: 9, subject: "physics", title: "Eylemsizlik Deneyi: Masa Örtüsü", description: "Newton'un 1. Hareket Yasası'nı (Eylemsizlik) gösterme.", instructions: "Bir masanın üzerine birkaç nesne koyup altındaki masa örtüsünü hızla çekerek eylemsizlik prensibini gösteren bir video çekin. Videoda olayı açıklayın.", formats: "Video, MP4", size: "30 MB" },
  { id: 936, grade: 9, subject: "physics", title: "Mutfakta Isı Transferi", description: "Isı aktarım yolları.", instructions: "Yemek yaparken tencerenin ısınması (iletim), suyun kaynaması (konveksiyon) ve fırının pişirmesi (ışıma) olaylarını mutfaktan fotoğraflarla anlat.", formats: "Görsel Sunum", size: "15 MB" },
  { id: 937, grade: 9, subject: "physics", title: "Enerji Dönüşüm Dedektifi", description: "Enerjinin korunumu ve enerji dönüşümleri.", instructions: "Bir oyuncak arabanın pille çalışmasından hareket etmesine kadar olan enerji dönüşüm zincirini (kimyasal -> elektrik -> kinetik) bir infografik ile anlatın.", formats: "Poster, JPG", size: "8 MB" },
  { id: 938, grade: 9, subject: "physics", title: "Basit Sarkaç Periyodu", description: "Periyot kavramını etkileyen değişkenler.", instructions: "Farklı uzunluklarda ipler ve farklı ağırlıklar kullanarak basit sarkaçlar yapın. Periyodun ipin uzunluğuna mı yoksa cismin kütlesine mi bağlı olduğunu test eden bir deney raporu yazın.", formats: "Word, PDF", size: "4 MB" },
  { id: 939, grade: 9, subject: "physics", title: "Yüzey Gerilimi Sanatı", description: "Sıvıların yüzey gerilimi özelliğini gösterme.", instructions: "Su dolu bir kaba yavaşça bir ataç veya jilet bırakarak yüzmesini sağlayın. Bu olayı videoya çekin ve yüzey gerilimi kavramıyla açıklayın.", formats: "Video", size: "20 MB" },
  { id: 940, grade: 9, subject: "physics", title: "Sürtünme Kuvvetini Ölçme", description: "Sürtünme kuvvetinin bağlı olduğu faktörler.", instructions: "Farklı yüzeylerde (halı, parke, zımpara kağıdı) bir cismi dinamometre ile çekerek sürtünme kuvvetini ölçün. Sonuçları bir tablo ile gösterip yorumlayın.", formats: "Word, JPG", size: "10 MB" },

  // 10. Sınıf Edebiyat
  { id: 1001, grade: 10, subject: "literature", title: "Divan'dan Sesleniş: Gazel Şerhi", description: "Seçilen bir gazelin günümüz diliyle yorumlanması.", instructions: "Fuzuli, Baki veya Nedim'den bir gazel seçerek beyit beyit günümüz Türkçesine çevirin ve ana temasını açıklayan bir kompozisyon yazın.", formats: "Word", size: "3 MB" },
  { id: 1002, grade: 10, subject: "literature", title: "Halkın Sesi: Mani Derlemesi", description: "Çevreden veya aile büyüklerinden mani derleme.", instructions: "Çevrenizden en az 10 farklı mani derleyerek bir video kaydı oluşturun. Manilerin temalarını (aşk, hasret, gurbet vb.) sınıflandırın.", formats: "Video, MP4", size: "50 MB" },
  { id: 1003, grade: 10, subject: "literature", title: "Mesnevi'den Hikmetler", description: "Mevlana'nın Mesnevi'sinden bir hikayeyi analiz etme.", instructions: "Mesnevi'den seçtiğiniz bir hikayeyi okuyun. Hikayenin ana fikrini ve içerdiği alegorik (sembolik) anlamları açıklayan bir sunum hazırlayın.", formats: "Canva, PDF", size: "8 MB" },
  { id: 1004, grade: 10, subject: "literature", title: "Karagöz ve Hacivat: Gölge Oyunu", description: "Basit bir Karagöz ve Hacivat diyaloğu yazma ve canlandırma.", instructions: "Güncel bir konu (örneğin sosyal medya) hakkında kısa bir Karagöz ve Hacivat diyaloğu yazın. Mümkünse basit figürlerle bu oyunu canlandırıp videosunu çekin.", formats: "Word, Video", size: "40 MB" },
  { id: 1005, grade: 10, subject: "literature", title: "Destan Kahramanı: Modern Bir Oğuz Kağan", description: "Oğuz Kağan Destanı'ndaki motifleri modern bir hikayeye uyarlama.", instructions: "Oğuz Kağan Destanı'ndaki olağanüstü doğum, ışık motifi gibi unsurları kullanarak günümüzde geçen bir süper kahraman hikayesi yazın.", formats: "Word", size: "5 MB" },
  { id: 1006, grade: 10, subject: "literature", title: "Koşma ve Semai Farkları", description: "Halk şiiri nazım biçimlerini karşılaştırma.", instructions: "Aşık Veysel'den bir koşma ve bir semai bularak bu iki şiiri; ölçü, kafiye şeması, konu ve dil bakımından karşılaştıran bir tablo hazırlayın.", formats: "PDF, Word", size: "2 MB" },
  { id: 1007, grade: 10, subject: "literature", title: "Nasreddin Hoca Fıkrası Analizi", description: "Bir Nasreddin Hoca fıkrasındaki mizah ve hiciv unsurlarını bulma.", instructions: "Seçtiğiniz bir Nasreddin Hoca fıkrasını anlatın ve fıkradaki nükteyi, eleştiriyi ve verilmek istenen dersi açıklayan bir metin yazın.", formats: "Word", size: "2 MB" },
  { id: 1008, grade: 10, subject: "literature", title: "Orta Oyunu Karakterleri Posteri", description: "Orta oyunundaki Pişekar ve Kavuklu tiplerini tanıtma.", instructions: "Pişekar ve Kavuklu'nun kostüm, konuşma özellikleri ve oyundaki rollerini anlatan görsel bir poster hazırlayın.", formats: "Poster, JPG", size: "12 MB" },
  { id: 1009, grade: 10, subject: "literature", title: "İlahi ve Nefes: Tasavvufi Şiir", description: "Yunus Emre'den bir ilahi ile Pir Sultan Abdal'dan bir nefesi karşılaştırma.", instructions: "Yunus Emre'den bir ilahi ve Pir Sultan Abdal'dan bir nefes bularak bu iki şiiri tema, dil ve temsil ettikleri inanç sistemi açısından karşılaştırın.", formats: "Word", size: "4 MB" },
  { id: 1010, grade: 10, subject: "literature", title: "Efsane Derleme", description: "Yaşanılan bölgeye ait bir efsaneyi araştırma ve kaydetme.", instructions: "Şehrinizle veya bölgenizle ilgili bir efsaneyi (Kız Kulesi Efsanesi, Sarıkız Efsanesi vb.) araştırın, farklı kaynaklardan derleyerek kendi üslubunuzla yeniden yazın.", formats: "PDF", size: "3 MB" },

  // 10. Sınıf Fizik
  { id: 1031, grade: 10, subject: "physics", title: "Basıncın Gücü", description: "Katı, sıvı ve gaz basıncı deneyleri.", instructions: "Evde basit malzemelerle (şişe, su, balon) Pascal prensibini veya açık hava basıncının etkisini gösteren kısa bir deney videosu çekin.", formats: "Video", size: "40 MB" },
  { id: 1032, grade: 10, subject: "physics", title: "Optik Yanılsamalar", description: "Gölge, yansıma ve kırılma olayları.", instructions: "Kaşığın sudan kırık görünmesi veya gölge boyunun değişimi gibi optik yanılsamaları fotoğraflayıp nedenlerini kısaca açıklayan bir sunum hazırlayın.", formats: "Görsel Sunum", size: "15 MB" },
  { id: 1033, grade: 10, subject: "physics", title: "Dalgaların Dansı", description: "Enine ve boyuna dalgaları modelleme.", instructions: "Bir yay veya ip kullanarak enine ve boyuna dalgaların nasıl oluştuğunu gösteren bir video çekin. Titreşim ve ilerleme doğrultuları arasındaki farkı videoda belirtin.", formats: "Video", size: "35 MB" },
  { id: 1034, grade: 10, subject: "physics", title: "Evdeki Elektrik Devresi", description: "Seri ve paralel bağlamanın farkları.", instructions: "İki ampul ve bir pil kullanarak önce seri, sonra paralel bir devre kurun. Ampul parlaklıklarındaki değişimi gözlemleyerek nedenini açıklayın.", formats: "Word, JPG", size: "8 MB" },
  { id: 1035, grade: 10, subject: "physics", title: "Mıknatısın Gizemi", description: "Manyetik alan çizgilerini görselleştirme.", instructions: "Bir çubuk mıknatısın etrafına demir tozları serperek manyetik alan çizgilerinin nasıl bir desen oluşturduğunu fotoğraflayın ve bu çizgilerin özelliklerini açıklayın.", formats: "JPG, PDF", size: "6 MB" },
  { id: 1036, grade: 10, subject: "physics", title: "Kaldırma Kuvveti", description: "Arşimet prensibini test etme.", instructions: "Farklı cisimleri suya batırarak dinamometre ile ağırlıklarındaki azalmayı ölçün. Cismin batan hacmi ile kaldırma kuvveti arasındaki ilişkiyi gösteren bir rapor yazın.", formats: "Word", size: "4 MB" },
  { id: 1037, grade: 10, subject: "physics", title: "Işığın Kırılması ve Renkler", description: "Prizma ile beyaz ışığı renklere ayırma.", instructions: "Bir prizma veya su dolu bir bardak kullanarak güneş ışığını gökkuşağı renklerine ayırın. Bu olayın nasıl gerçekleştiğini açıklayan bir poster hazırlayın.", formats: "Poster, JPG", size: "10 MB" },
  { id: 1038, grade: 10, subject: "physics", title: "Sesin Hızı", description: "Sesin farklı ortamlardaki yayılma hızını karşılaştırma.", instructions: "Sesin havada, suda ve katıda (örneğin bir masa) nasıl yayıldığını ve hızının neden farklı olduğunu anlatan bir infografik tasarlayın.", formats: "Canva, PDF", size: "5 MB" },
  { id: 1039, grade: 10, subject: "physics", title: "Ohm Yasası Doğrulaması", description: "Gerilim, akım ve direnç arasındaki ilişki.", instructions: "Basit bir devrede, gerilimi değiştirerek akımda meydana gelen değişiklikleri ölçün. Ölçümlerinizi kullanarak bir Gerilim-Akım grafiği çizin ve bu grafikten direnci hesaplayın.", formats: "Word, PDF", size: "3 MB" },
  { id: 1040, grade: 10, subject: "physics", title: "Aynadaki Görüntüm", description: "Düzlem, çukur ve tümsek aynalarda görüntü oluşumu.", instructions: "Bir kaşığın iç ve dış yüzeyini ayna olarak kullanarak oluşan görüntülerin (düz, ters, büyük, küçük) özelliklerini karşılaştıran bir tablo hazırlayın.", formats: "Word", size: "2 MB" },

  // 11. Sınıf Edebiyat
  { id: 1101, grade: 11, subject: "literature", title: "Tanzimat'tan Portreler: Podcast Serisi", description: "Tanzimat dönemi bir yazarını tanıtma.", instructions: "Namık Kemal, Şinasi veya Ziya Paşa gibi bir Tanzimat yazarının hayatını, eserlerini ve fikirlerini anlatan bir podcast bölümü hazırlayın.", formats: "Ses Kaydı, MP3", size: "20 MB" },
  { id: 1102, grade: 11, subject: "literature", title: "Modern Roman İncelemesi", description: "Servetifünun veya Milli Edebiyat döneminden bir romanı inceleme.", instructions: "Halit Ziya'nın 'Aşk-ı Memnu' veya Yakup Kadri'nin 'Yaban' romanının ana karakterlerini, çatışmalarını ve dönemin zihniyetini yansıtan yönlerini analiz eden bir makale yazın.", formats: "PDF, Word", size: "5 MB" },
  { id: 1103, grade: 11, subject: "literature", title: "Batı Etkisindeki Türk Şiiri", description: "Tanzimat, Servetifünun ve Fecriati şiirini karşılaştırma.", instructions: "Her dönemden bir şair seçerek (örn: Tevfik Fikret, Cenap Şahabettin, Ahmet Haşim) şiirlerini tema, dil ve ahenk unsurları açısından karşılaştıran bir sunum hazırlayın.", formats: "Canva, PDF", size: "10 MB" },
  { id: 1104, grade: 11, subject: "literature", title: "Eleştiri Sanatı: Makale Analizi", description: "Namık Kemal'in bir eleştiri yazısını inceleme.", instructions: "'Tahrib-i Harabat' veya 'Takip' gibi bir eleştiri metnini okuyarak Namık Kemal'in eleştiri anlayışını, kullandığı dil ve üslubu analiz edin.", formats: "Word", size: "4 MB" },
  { id: 1105, grade: 11, subject: "literature", title: "Saf Şiir (Öz Şiir) Manifestosu", description: "Saf şiir anlayışını açıklayan bir manifesto yazma.", instructions: "Ahmet Haşim ve Yahya Kemal'in şiir anlayışlarından yola çıkarak 'Şiirde önemli olan anlam değil, musiki ve histir' fikrini savunan yaratıcı bir manifesto metni oluşturun.", formats: "PDF", size: "2 MB" },
  { id: 1106, grade: 11, subject: "literature", title: "Milli Edebiyat'ta Yeni Lisan", description: "Yeni Lisan hareketinin ilkelerini araştırma.", instructions: "Ömer Seyfettin ve arkadaşlarının başlattığı Yeni Lisan hareketinin temel ilkelerini (dilde sadeleşme, İstanbul Türkçesi vb.) araştırarak bir bilgi kartı (infografik) hazırlayın.", formats: "Poster, JPG", size: "8 MB" },
  { id: 1107, grade: 11, subject: "literature", title: "Sokağı Edebiyata Taşıyan Adam: Hüseyin Rahmi", description: "Hüseyin Rahmi Gürpınar'ın bir romanında toplum eleştirisi.", instructions: "'Şıpsevdi' veya 'Gulyabani' romanından hareketle Hüseyin Rahmi'nin eski ve yeni yaşam tarzı, batıl inançlar gibi konulardaki toplum eleştirisini örneklerle açıklayın.", formats: "Word", size: "5 MB" },
  { id: 1108, grade: 11, subject: "literature", title: "'Sis' Şiiri ve İstanbul", description: "Tevfik Fikret'in 'Sis' şiirindeki karamsar İstanbul tasvirini analiz etme.", instructions: "Tevfik Fikret'in 'Sis' şiirini okuyun ve şairin dönemin İstanbul'una yönelik nefretini, karamsarlığını yansıtan dize ve imgeleri bularak yorumlayın.", formats: "Word", size: "3 MB" },
  { id: 1109, grade: 11, subject: "literature", title: "Beş Hececiler: Şiir Seslendirmesi", description: "Beş Hececiler'den bir şairin şiirini seslendirme.", instructions: "Faruk Nafiz Çamlıbel veya Orhan Seyfi Orhon gibi bir şairin, memleket sevgisini işleyen bir şiirini, dönemin ruhuna uygun bir tonla seslendirerek video kaydı oluşturun.", formats: "Video", size: "25 MB" },
  { id: 1110, grade: 11, subject: "literature", title: "Fecriati Bildirisi", description: "Fecriati topluluğunun sanat anlayışını özetleme.", instructions: "Fecriati topluluğunun yayımladığı bildiriyi bularak 'Sanat, şahsi ve muhteremdir' sözü ekseninde sanat anlayışlarını özetleyen bir sunum hazırlayın.", formats: "Canva, PDF", size: "6 MB" },

  // 11. Sınıf Fizik
  { id: 1131, grade: 11, subject: "physics", title: "Vektörel Kuvvet Dengesi", description: "Bir cisme etki eden kuvvetlerin dengesi.", instructions: "Bir avize veya saksının asılı durduğu durumu analiz edin. İplerdeki gerilme kuvvetlerini vektörlerle göstererek serbest cisim diyagramını çizin ve açıklayın.", formats: "JPG, PDF", size: "5 MB" },
  { id: 1132, grade: 11, subject: "physics", title: "Alternatif Akımın İzinde", description: "Doğru akım ve alternatif akımın karşılaştırılması.", instructions: "Evimizdeki prizlerin neden alternatif akım kullandığını, pillerin ise neden doğru akım kaynağı olduğunu araştırıp avantaj ve dezavantajlarını listeleyen bir sunum hazırlayın.", formats: "Görsel Sunum", size: "10 MB" },
  { id: 1133, grade: 11, subject: "physics", title: "Tork ve Denge", description: "Tork prensibini kullanarak bir denge sistemi kurma.", instructions: "Bir cetvel, silgi ve birkaç madeni para kullanarak basit bir tahterevalli sistemi kurun. Farklı noktalara paraları koyarak dengeyi nasıl sağladığınızı gösterin ve tork formülü ile hesaplamalarınızı doğrulayın.", formats: "Word, Video", size: "30 MB" },
  { id: 1134, grade: 11, subject: "physics", title: "İtme ve Momentum Korunumu", description: "Çarpışmalarda momentumun korunumunu gösterme.", instructions: "İki veya daha fazla misketi birbiriyle çarpıştırarak momentumun korunumunu gösteren bir video çekin. Çarpışma öncesi ve sonrası toplam momentumu nasıl korunduğunu açıklayın.", formats: "Video", size: "40 MB" },
  { id: 1135, grade: 11, subject: "physics", title: "Basit Harmonik Hareket: Yay Sarkacı", description: "Yay sarkacının periyodunu etkileyen faktörler.", instructions: "Bir yaya farklı kütleler asarak salınım periyotlarını ölçün. Periyodun kütleye ve yay sabitine nasıl bağlı olduğunu gösteren bir grafik çizin ve yorumlayın.", formats: "Word, PDF", size: "4 MB" },
  { id: 1136, grade: 11, subject: "physics", title: "Transformatör Yapımı", description: "Basit bir transformatör modeli oluşturma.", instructions: "İki farklı sarım sayılı bobin ve bir demir çekirdek kullanarak basit bir yükseltici veya alçaltıcı transformatör modeli yapın. Giriş ve çıkış gerilimlerini ölçerek çalışma prensibini açıklayın.", formats: "JPG, Word", size: "12 MB" },
  { id: 1137, grade: 11, subject: "physics", title: "Elektriksel Potansiyel Enerji", description: "Yüklü cisimlerin etkileşimini modelleme.", instructions: "İki balonu yün kumaşa sürterek yükleyin ve birbirlerini nasıl ittiklerini gözlemleyin. Bu itme kuvvetinin kaynağı olan elektriksel potansiyel enerjiyi açıklayan bir rapor yazın.", formats: "Word", size: "3 MB" },
  { id: 1138, grade: 11, subject: "physics", title: "Paralel Levhalar", description: "Düzgün elektrik alan içinde yüklü parçacığın hareketi.", instructions: "Paralel levhalar arasındaki düzgün elektrik alanı ve bu alanda bir elektronun nasıl saptığını gösteren bir çizim yapın. Televizyon tüplerinin çalışma prensibiyle ilişkilendirin.", formats: "JPG, PDF", size: "5 MB" },
  { id: 1139, grade: 11, subject: "physics", title: "Manyetik Akı ve İndüksiyon", description: "Faraday'ın İndüksiyon Yasası.", instructions: "Bir bobinin içinden bir mıknatısı hızla geçirirken bir voltmetreye bağlayarak nasıl elektrik akımı (indüksiyon akımı) oluşturulduğunu gösteren bir deney videosu çekin.", formats: "Video", size: "35 MB" },
  { id: 1140, grade: 11, subject: "physics", title: "Kütle Çekim Potansiyel Enerjisi", description: "Gezegenlerin yörünge hareketi.", instructions: "Güneş sistemindeki bir gezegenin, Güneş'e yaklaşıp uzaklaşırken hızının ve potansiyel enerjisinin nasıl değiştiğini anlatan bir animasyon veya çizim serisi hazırlayın.", formats: "Canva, GIF", size: "15 MB" },

  // 12. Sınıf Edebiyat
  { id: 1201, grade: 12, subject: "literature", title: "Cumhuriyet Şiirinde Bir Ses: Video Analiz", description: "Bir Cumhuriyet dönemi şairini ve şiir anlayışını tanıtma.", instructions: "Necip Fazıl, Nazım Hikmet, Orhan Veli veya Cemal Süreya gibi bir şairin şiir anlayışını ve en az iki şiirini yorumlayan bir video analiz hazırlayın.", formats: "Video", size: "60 MB" },
  { id: 1202, grade: 12, subject: "literature", title: "Postmodern Anlatı: Roman İncelemesi", description: "Postmodern bir romanda kullanılan anlatım teknikleri.", instructions: "Orhan Pamuk'un 'Benim Adım Kırmızı' veya 'Kara Kitap' romanındaki üstkurmaca, metinlerarasılık gibi postmodern teknikleri bularak örneklerle açıklayan bir inceleme yazısı yazın.", formats: "Word", size: "4 MB" },
  { id: 1203, grade: 12, subject: "literature", title: "Bireyin İç Dünyası: Psikolojik Roman", description: "Peyami Safa'nın 'Dokuzuncu Hariciye Koğuşu' romanını analiz etme.", instructions: "'Dokuzuncu Hariciye Koğuşu' romanındaki hasta çocuğun iç dünyasını, ruh tahlillerini ve anlatıcı-kahraman bakış açısının etkilerini inceleyen bir makale yazın.", formats: "PDF, Word", size: "5 MB" },
  { id: 1204, grade: 12, subject: "literature", title: "Toplumcu Gerçekçi Bakış", description: "Sabahattin Ali'nin bir hikayesinde toplumsal eleştiri.", instructions: "Sabahattin Ali'nin 'Kuyucaklı Yusuf' veya 'Sırça Köşk' gibi bir eserinden hareketle, dönemin toplumsal sorunlarına (adaletsizlik, eşitsizlik) nasıl ayna tuttuğunu analiz edin.", formats: "Word", size: "4 MB" },
  { id: 1205, grade: 12, subject: "literature", title: "İkinci Yeni Şiiri: Anlamsızlığın Anlamı", description: "İkinci Yeni şiirinin temel özelliklerini görselleştirme.", instructions: "Cemal Süreya, Edip Cansever veya Turgut Uyar'dan seçtiğiniz bir şiirden yola çıkarak, İkinci Yeni'nin imgeye dayalı, soyut ve kapalı anlatımını yansıtan bir kolaj veya dijital sanat çalışması yapın.", formats: "JPG, Canva", size: "15 MB" },
  { id: 1206, grade: 12, subject: "literature", title: "Modernist Tiyatro: Absürt Tiyatro", description: "Güner Sümer'in 'Hüzzam' oyununu inceleme.", instructions: "Absürt tiyatronun özelliklerini araştırın ve 'Hüzzam' oyununun bu özelliklerle (iletişimsizlik, beklenti vb.) nasıl örtüştüğünü gösteren bir rapor hazırlayın.", formats: "PDF", size: "3 MB" },
  { id: 1207, grade: 12, subject: "literature", title: "Köy Romanı ve Gerçeklik", description: "Yaşar Kemal'in 'İnce Memed' romanında Çukurova.", instructions: "Yaşar Kemal'in 'İnce Memed' romanında Çukurova'nın doğasını, toplumsal yapısını ve ağalık sistemini nasıl betimlediğini araştırarak bir sunum hazırlayın.", formats: "Canva, PDF", size: "10 MB" },
  { id: 1208, grade: 12, subject: "literature", title: "Hisarcılar ve Gelenek", description: "Hisarcılar topluluğunun sanat anlayışını tartışma.", instructions: "Hisarcılar topluluğunun 'geleneğe bağlı kalarak yenilik yapma' ilkesini, Mehmet Çınarlı veya İlhan Geçer'in bir şiiri üzerinden tartışan bir eleştiri yazısı yazın.", formats: "Word", size: "3 MB" },
  { id: 1209, grade: 12, subject: "literature", title: "Varoluşçuluk ve Edebiyat", description: "Demir Özlü veya Ferit Edgü'nün bir eserinde varoluşçu temalar.", instructions: "Seçtiğiniz bir eserdeki karakterin yaşadığı yabancılaşma, bunaltı, saçma ve özgürlük gibi varoluşçu temaları analiz eden bir podcast bölümü hazırlayın.", formats: "Ses Kaydı, MP3", size: "25 MB" },
  { id: 1210, grade: 12, subject: "literature", title: "Mitolojiden Moderne: Şiirde Metinlerarasılık", description: "Melih Cevdet Anday'ın 'Kolları Bağlı Odysseus' şiirini inceleme.", instructions: "'Kolları Bağlı Odysseus' şiirinin, Homeros'un Odysseia destanıyla kurduğu metinlerarası ilişkiyi ve modern insanın trajedisini nasıl yansıttığını inceleyin.", formats: "Word, PDF", size: "4 MB" },
  
  // 12. Sınıf Fizik
  { id: 1231, grade: 12, subject: "physics", title: "Çembersel Hareketin Sırları", description: "Merkezcil kuvveti gösteren bir model yapma.", instructions: "Bir ipin ucuna bağladığınız bir cismi döndürerek çembersel hareket yaptırın. İpteki gerilmenin (merkezcil kuvvet) nelere bağlı olduğunu (hız, yarıçap) açıklayan bir video çekin.", formats: "Video", size: "30 MB" },
  { id: 1232, grade: 12, subject: "physics", title: "Dalga Mekaniği: Kırınım ve Girişim", description: "Su dalgalarında kırınım ve girişim desenlerini gözlemleme.", instructions: "Su dolu bir leğende iki engel arasından geçen veya iki noktasal kaynağın oluşturduğu dalgaların girişim desenini videoya çekerek dalga tepelerini ve çukurlarını işaretleyin.", formats: "Video, JPG", size: "40 MB" },
  { id: 1233, grade: 12, subject: "physics", title: "Doppler Etkisi Simülasyonu", description: "Ses dalgalarında Doppler etkisini modelleme.", instructions: "Yaklaşan ve uzaklaşan bir ambulansın siren sesinin frekansının nasıl değiştiğini bir çizim, animasyon veya ses efekti kullanarak anlatan bir sunum hazırlayın.", formats: "Canva, GIF, MP3", size: "15 MB" },
  { id: 1234, grade: 12, subject: "physics", title: "Siyah Cisim Işıması ve Kuantuma Giriş", description: "Siyah cisim ışıması grafiğini yorumlama.", instructions: "Farklı sıcaklıklardaki bir cismin yaydığı ışımanın şiddet-dalga boyu grafiğini (siyah cisim ışıması) çizin. Planck'ın bu grafiği klasik fizikle neden açıklayamadığını araştırın.", formats: "PDF, Word", size: "3 MB" },
  { id: 1235, grade: 12, subject: "physics", title: "Fotoelektrik Olay: Einstein'ın Dehası", description: "Fotoelektrik olayın prensiplerini açıklama.", instructions: "Bir metal yüzeye düşen ışığın elektron sökmesini (fotoelektrik olay) ve bu olayın sadece tanecik modeliyle açıklanabildiğini gösteren bir infografik hazırlayın.", formats: "Poster, JPG", size: "10 MB" },
  { id: 1236, grade: 12, subject: "physics", title: "Compton Saçılması", description: "Fotonların momentumu olduğunu gösterme.", instructions: "Bir fotonun bir elektrona çarparak saçılmasını (Compton olayı) gösteren bir serbest cisim diyagramı çizin. Bu olayın, ışığın tanecik doğasını nasıl kanıtladığını açıklayın.", formats: "JPG, PDF", size: "4 MB" },
  { id: 1237, grade: 12, subject: "physics", title: "De Broglie Dalgası: Her Parçacık Bir Dalga mı?", description: "Maddenin dalga-parçacık ikiliğini açıklama.", instructions: "Hareket eden bir futbol topunun ve bir elektronun De Broglie dalga boylarını hesaplayın. Neden makroskopik cisimlerin dalga özelliğini gözlemleyemediğimizi açıklayın.", formats: "Word", size: "2 MB" },
  { id: 1238, grade: 12, subject: "physics", title: "Büyük Patlama'nın Kanıtları", description: "Evrenin oluşumu ve genişlemesi.", instructions: "Hubble Yasası (kırmızıya kayma) ve Kozmik Mikrodalga Arka Plan Işıması'nın Büyük Patlama teorisini nasıl desteklediğini anlatan bir infografik tasarlayın.", formats: "Poster, JPG", size: "10 MB" },
  { id: 1239, grade: 12, subject: "physics", title: "Radyoaktivite ve Yarı Ömür", description: "Radyoaktif bozunmayı modelleme.", instructions: "100 adet madeni parayı aynı anda atarak ve tura gelenleri her seferinde çıkararak radyoaktif bozunma sürecini simüle edin. Kalan para sayısını atış sayısına göre grafiğe dökerek yarı ömür kavramını açıklayın.", formats: "Word, PDF, JPG", size: "5 MB" },
  { id: 1240, grade: 12, subject: "physics", title: "GPS ve Zaman Kayması", description: "Özel ve genel görelilik.", instructions: "Uydulardaki saatlerin dünyadaki saatlerden neden farklı çalıştığını ve Einstein'ın görelilik teorilerinin GPS doğruluğu için önemini anlatan bir video hazırlayın.", formats: "Video", size: "25 MB" }
];

export const initialRubricDefinitions = {
  research: {
    title: "Araştırma ve Yazma Rubriği",
    description: "Makale, Rapor, Hikaye, Deneme türü ödevler için standart değerlendirme.",
    items: [
      { label: "İçerik Doğruluğu ve Zenginliği", score: 40, desc: "Konu tam ve doğru anlatılmış mı? Bilgi eksikliği var mı?" },
      { label: "Dil ve Anlatım (İmla/Noktalama)", score: 20, desc: "Yazım kurallarına uyulmuş mu? Akıcı bir dil kullanılmış mı?" },
      { label: "Özgünlük ve Yorum", score: 20, desc: "Kopya içerik var mı? Öğrenci kendi yorumunu katmış mı?" },
      { label: "Düzen ve Kaynakça", score: 20, desc: "Sayfa düzeni temiz mi? Yararlanılan kaynaklar belirtilmiş mi?" }
    ]
  },
  multimedia: {
    title: "Multimedya ve Sunum Rubriği",
    description: "Video, Ses Kaydı, Animasyon türü ödevler için standart değerlendirme.",
    items: [
      { label: "İçerik ve Konuya Hakimiyet", score: 30, desc: "Videoda anlatılan bilgiler doğru ve konuyla ilgili mi?" },
      { label: "Yaratıcılık ve Kurgu", score: 30, desc: "Senaryo özgün mü? İlgi çekici bir kurgu var mı?" },
      { label: "İletişim ve Diksiyon", score: 20, desc: "Ses net anlaşılıyor mu? Akıcı bir anlatım var mı?" },
      { label: "Teknik Kalite (Görüntü/Ses)", score: 20, desc: "Görüntü net mi? Ses cızırtılı mı? Süreye uyulmuş mu?" }
    ]
  },
  visual: {
    title: "Görsel Tasarım Rubriği",
    description: "Poster, İnfografik, Dergi Kapağı türü ödevler için standart değerlendirme.",
    items: [
      { label: "Görsel Düzen ve Estetik", score: 30, desc: "Renk uyumu, yerleşim ve okunabilirlik iyi mi?" },
      { label: "Konuyu Görselleştirme", score: 30, desc: "Görseller konuyla alakalı mı? Mesajı doğru iletiyor mu?" },
      { label: "Yaratıcılık", score: 20, desc: "Sıradan görseller yerine özgün tasarımlar kullanılmış mı?" },
      { label: "Özen ve Emek", score: 20, desc: "Tasarım detaylarına dikkat edilmiş mi? Baştan savma mı?" }
    ]
  }
};

// Ödev tipine göre otomatik rubrik seçici
export const getRubricType = (formats: string) => {
  if (formats.includes("Video") || formats.includes("MP4") || formats.includes("Ses") || formats.includes("MP3")) return 'multimedia';
  if (formats.includes("Canva") || formats.includes("JPG") || formats.includes("Poster") || formats.includes("Fotoğraf") || formats.includes("Görsel")) return 'visual';
  return 'research';
};
